NUM_WORKER_NODES=2
IP_NW="192.168.62."
IP_START=10

Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        yum update -y
        echo "$IP_NW$((IP_START))  ansible" >> /etc/hosts
        echo "$IP_NW$((IP_START+1))  master-node" >> /etc/hosts
        echo "$IP_NW$((IP_START+2))  worker-node01" >> /etc/hosts
        echo "$IP_NW$((IP_START+3))  worker-node02" >> /etc/hosts
    SHELL

    config.vm.box = "centos7"
    config.vm.box_check_update = true

	
    config.vm.define "ansible" do |ansible|
      master.vm.hostname = "ansible"
      master.vm.network "private_network", ip: IP_NW + "#{IP_START}"
      master.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 2
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
#      master.vm.provision "shell", path: "scripts/common.sh"
#      master.vm.provision "shell", path: "scripts/master.sh"
    end

    config.vm.define "master" do |master|
      master.vm.hostname = "master-node"
      master.vm.network "private_network", ip: IP_NW + "#{IP_START}"
      master.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 2
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
#      master.vm.provision "shell", path: "scripts/common.sh"
#      master.vm.provision "shell", path: "scripts/master.sh"
    end

    (1..NUM_WORKER_NODES).each do |i|
      config.vm.define "node0#{i}" do |node|
        node.vm.hostname = "worker-node0#{i}"
        node.vm.network "private_network", ip: IP_NW + "#{IP_START + i}"
        node.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
#        node.vm.provision "shell", path: "scripts/common.sh"
#        node.vm.provision "shell", path: "scripts/node.sh"
      end
    end
end
